.PHONY: run run-unoptimized run-compiler-optimized run-simple-concurrent run-simple-concurrent-unoptimized

run-compiler-optimized:
	cargo run --release

run:
	cargo run --profile release-unoptimized

run-simple-concurrent:
	cargo run --bin simple_concurrent --profile release-unoptimized

