services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cache_patterns
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/MAJOR/docker

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
